[ldapenforcer]
# LDAP Connection Settings
# URI for connecting to LDAP server (required)
# Use ldap:// for standard connections or ldaps:// for secure connections
uri = "ldap://example.com:389"
# uri = "ldaps://example.com:636"  # Example for secure LDAPS connection

# DN for binding to LDAP (required)
bind_dn = "cn=admin,dc=example,dc=com"

# Password for binding to LDAP (one of password, password_file, or password_command must be provided)
password = "admin_password"
# OR
# password_file = "/path/to/password/file.txt"  # Absolute path
# password_file = "relative/path/to/password.txt"  # Relative to config file
# OR
# password_command = "pass show ldap/admin"  # Execute command to get password
# password_command = "security find-generic-password -s 'LDAP Admin' -w"  # macOS keychain example
# password_command = "secret-tool lookup service ldap user admin"  # GNOME keyring example
# password_command = "kubectl get secret -n directory dirsrv-env -o go-template='{{ index .data \"DS_DM_PASSWORD\" | base64decode}}'"
#
# For commands that need shell features (|, <, >, $, ``, etc.), set password_command_via_shell = true
# Example with kubectl and go-templates (requires password_command_via_shell = true):
# password_command = "somehow-get-password | grep 'password:' | awk '{print $2}'"
# password_command_via_shell = true

# Path to CA certificate file for LDAPS connections (only needed for LDAPS)
# ca_cert_file = "/path/to/ca.crt"  # Absolute path
# ca_cert_file = "certs/ca.crt"  # Relative to config file
#
# NOTE: All configuration settings can also be set via environment variables.
# Environment variable names are in the format LDAPENFORCER_<SETTING_NAME>,
# for example:
#   - LDAPENFORCER_URI
#   - LDAPENFORCER_BIND_DN
#   - LDAPENFORCER_PASSWORD
#   - LDAPENFORCER_LOG_LEVEL
#   - LDAPENFORCER_LDAP_LOG_LEVEL
#   - LDAPENFORCER_PEOPLE_BASE_DN
# Environment variables take precedence over config file settings.

# Directory Structure
# Full OU for enforced people (required)
enforced_people_ou = "ou=managed,ou=people,dc=example,dc=com"

# Full OU for enforced service accounts (required)
enforced_svcacct_ou = "ou=managed,ou=svcaccts,dc=example,dc=com"

# Full OU for enforced groups (required)
enforced_group_ou = "ou=managed,ou=groups,dc=example,dc=com"

# Config polling is now a CLI argument only
# Use --poll to specify a polling interval in seconds
# Example: ldapenforcer sync --poll 10

# Include files - paths are relative to this config file's directory
# unless they are absolute paths
includes = [
    # "additional-config.toml",
    # "/absolute/path/to/config.toml"
]

# Logging configuration
# Main application log level
# Valid values: ERROR, WARN, INFO, DEBUG, TRACE (case-insensitive)
# ERROR: Only error messages (default)
# WARN: Warnings and errors
# INFO: Informational messages, warnings, and errors
# DEBUG: Debug messages and all above
# TRACE: Trace messages (extremely verbose) and all above
main_log_level = "ERROR"

# LDAP-specific log level (can be different from main log level)
# Use DEBUG or TRACE level to enable detailed LDAP protocol logging
# without increasing verbosity of other application logs.
ldap_log_level = "ERROR"
