version: '3.8'

services:
  ldapenforcer:
    build:
      context: .
      dockerfile: Dockerfile
    image: ldapenforcer:latest
    volumes:
      - ./config.toml:/etc/ldapenforcer/config.toml:ro
    command: ["sync", "--config", "/etc/ldapenforcer/config.toml", "--config-poll-interval", "5"]
    restart: unless-stopped
    # Optional environment variables for configuration - override config file values
    environment:
      - LDAPENFORCER_LOG_LEVEL=INFO
      # - LDAPENFORCER_URI=ldap://example.com:389
      # - LDAPENFORCER_BIND_DN=cn=admin,dc=example,dc=com
      # - LDAPENFORCER_PASSWORD=changeme