[ldapenforcer]
uri = "ldap://testfile.example.com:389"
bind_dn = "cn=testfile,dc=example,dc=com"
password = "test_password"
people_base_dn = "ou=people,dc=example,dc=com"
svcacct_base_dn = "ou=svcaccts,dc=example,dc=com"
group_base_dn = "ou=testgroups,dc=example,dc=com"
managed_ou = "test-managed"
includes = ["include.toml"]