name: Master Build

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./...

      - name: Run GoReleaser (snapshot)
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: 2
          args: build --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create a temporary artifact that is stored for just `retention-days` days
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ldapenforcer-master
          path: dist/*/ldapenforcer*
          retention-days: 5
